#!/bin/bash
#
# Shut down Lobsang through the python library.
# It does use  'sudo halt'  but there is a  bit
# more  to it than  that such as  archiving the
# logfile and making the Duino LED go  solid on
# until the Pi has fully shut down.
#
# Created Aug 2016 by Finley Watson.

cd /home/pi/lobsang/
sudo python -c "import Lobsang; Lobsang.halt()"
exit 0
